config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  get 'items/search'
  resources :users, only: [:edit, :update]
  resources :items do
    resources :buyers, only: [:index,:create]
  end
end

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), root_path %>
     <%= form_with(url: items_search_path, local: true, method: :get, class: "search-form") do |form| %>
     <%= form.text_field :keyword, placeholder:  'キーワードから探す' , class: "search-input" %>
     <%= form.label :submit, class: "search-button" do %>
     <%= image_tag "search.png", class:"search-icon" %>
     <% end %>
     <%= form.submit :submit, id: "submit", style: "display: none;"%>
  <% end %>



  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', root_path, class: "category-list" %></li>
      <li><%= link_to 'ブランド', root_path, class: "brand-list" %></li>
    </ul>
   <% if user_signed_in? %>
    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <li><%= link_to current_user.nickname, root_path, class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,  class: "logout" %></li> 
   <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
    <% end %>
  </div>
</header>